### ISSUE TITLE
GetGridBehavior command silently failing on stations with passive behavior.

### ISSUE THREAD

**Issue by MeridiusIX** [MeridiusIX/Modular-Encounters-Systems#108]
```
2021-10-09 10-15-47-964: MES / Error: System.NullReferenceException: Object reference not set to an instance of an object.
   at ModularEncountersSystems.Behavior.Subsystems.AutoPilot.AutoPilotSystem.GetAutopilotData()
   at ModularEncountersSystems.Behavior.CoreBehavior.ToString()
   at ModularEncountersSystems.Logging.LoggerTools.GetGridBehavior(ChatMessage message)
   at ModularEncountersSystems.Sync.ChatMessage.ProcessInfo()
   at ModularEncountersSystems.Sync.ChatMessage.ProcessChat()
   at ModularEncountersSystems.Sync.ChatManager.ProcessServerChat(ChatMessage chatData)
   at ModularEncountersSystems.Sync.ChatManager.ChatReceivedNetwork(ChatMessage chatData)
   at ModularEncountersSystems.Sync.SyncManager.NetworkMessageReceiver(UInt16 handlerId, Byte[] initialData, UInt64 sender, Boolean fromServer)
   ```

**Comment by MeridiusIX** [comment]
Resolving by not printing autopilot data for passive behavior. will reopen in behavior persists on other subclasses
