### ISSUE TITLE
Fix exception in autoPilot gyro LimitSpeed method

### ISSUE THREAD

**Issue by MeridiusIX** [MeridiusIX/Modular-Encounters-Systems#127]
```
2021-11-17 13:27:23.495 - Thread:   9 ->  MES / General: System.ArithmeticException: Function does not accept floating point Not-a-Number values.
   at System.Math.Sign(Single value)
   at ModularEncountersSystems.Behavior.Subsystems.AutoPilot.AutoPilotSystem.LimitSpeed(Single proposedSpeed, Double actualSpeed)
   at ModularEncountersSystems.Behavior.Subsystems.AutoPilot.AutoPilotSystem.CalculateGyroRotation()
   at ModularEncountersSystems.Behavior.Subsystems.AutoPilot.AutoPilotSystem.ProcessRotationParallel(Boolean hasWaypoint)
   at ModularEncountersSystems.Behavior.Subsystems.AutoPilot.AutoPilotSystem.PrepareAutopilot()
   at ModularEncountersSystems.Behavior.CoreBehavior.ProcessAutoPilotChecks()
   at ModularEncountersSystems.Behavior.BehaviorManager.ProcessAutoPilotParallel()
   at ModularEncountersSystems.Behavior.BehaviorManager.<>c.<ProcessParallelMethods>b__17_0()
   ```

**Comment by MeridiusIX** [comment]
Should be fixed in next update

**Comment by Synirrr** [comment]
This is still occurring as of Feb. 27 2024
