### ISSUE TITLE
Crash in Loot Profile Processing

### ISSUE THREAD

**Issue by MeridiusIX** [MeridiusIX/Modular-Encounters-Systems#165]
2022-02-13 00:49:29.117 - Thread:   1 ->  Exception occurred: System.NullReferenceException: Object reference not set to an instance of an object.
   at ModularEncountersSystems.Spawning.Manipulation.PrefabInventory.ApplyLootProfiles(PrefabContainer prefab, ManipulationProfile profile)
   at ModularEncountersSystems.Spawning.Manipulation.PrefabManipulation.ProcessManipulations(PrefabContainer prefab, SpawnGroupCollection collection, ManipulationProfile profile, EnvironmentEvaluation environment, NpcData data)
   at ModularEncountersSystems.Spawning.Manipulation.PrefabManipulation.PrepareManipulations(PrefabContainer prefab, SpawnGroupCollection collection, EnvironmentEvaluation environment, NpcData data)
   at ModularEncountersSystems.Spawning.PrefabSpawner.SpawnPrefab(SpawnGroupCollection spawnCollection, PathDetails path, EnvironmentEvaluation environment)
   at ModularEncountersSystems.Spawning.PrefabSpawner.ProcessSpawning(SpawnGroupCollection spawnCollection, PathDetails path, EnvironmentEvaluation environment)
   at ModularEncountersSystems.Spawning.SpawnRequest.CalculateSpawn(Vector3D coords, String source, SpawningType type, Boolean forceSpawn, Boolean adminSpawn, List`1 eligibleNames, String factionOverride, MatrixD spawnMatrix, Vector3D customVelocity)
   at ModularEncountersSystems.API.LocalApi.SpawnPlanetaryCargoShip(Vector3D coords, List`1 spawnGroups)
   at SupplyDrops.MES.API.MESApi.SpawnPlanetaryCargoShip(Vector3D coords, List`1 spawnGroups)
   at SupplyDrops.SupplyDrops.Players_ItemConsumed(IMyCharacter player, MyDefinitionId consumed)
   at System.Action`2.Invoke(T1 arg1, T2 arg2)
   at Sandbox.Game.MyInventory.InventoryConsumeItem_Implementation(MyFixedPoint amount, SerializableDefinitionId itemId, Int64 consumerEntityId)
   at Sandbox.Game.MyInventory.InventoryConsumeItem_Implementation<>VRage_MyFixedPoint#VRage_ObjectBuilders_SerializableDefinitionId#System_Int64.Invoke(MyInventory& this, MyFixedPoint& amount, SerializableDefinitionId& itemId, Int64& consumerEntityId, DBNull& arg4, DBNull& arg5, DBNull& arg6)
   at VRage.Network.MyReplicationLayerBase.InvokeLocally[T1,T2,T3,T4,T5,T6,T7](CallSite`7 site, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7)
   at VRage.Network.MyReplicationSingle.DispatchEvent[T1,T2,T3,T4,T5,T6,T7,T8](CallSite callSite, EndpointId recipient, Nullable`1 position, T1& arg1, T2& arg2, T3& arg3, T4& arg4, T5& arg5, T6& arg6, T7& arg7, T8& arg8)
   at VRage.Network.MyReplicationLayerBase.RaiseEvent[T1,T2,T3,T4,T5](T1 arg1, T5 arg5, Func`2 action, T2 arg2, T3 arg3, T4 arg4, EndpointId endpointId, Nullable`1 position)
   at Sandbox.Game.MyInventory.ConsumeItem(MyDefinitionId itemId, MyFixedPoint amount, Int64 consumerEntityId)
   at Sandbox.Game.Screens.Helpers.MyToolbarItemUsable.Activate()
   at Sandbox.Game.Screens.Helpers.MyToolbar.ActivateItemAtIndex(Int32 index, Boolean checkIfWantsToBeActivated)
   at Sandbox.Game.Screens.Helpers.MyToolbar.ActivateItemAtSlot(Int32 slot, Boolean checkIfWantsToBeActivated, Boolean playActivationSound, Boolean userActivated)
   at Sandbox.Game.Screens.Helpers.MyToolbarComponent.HandleInput()
   at Sandbox.Game.World.MySession.HandleInput()
   at Sandbox.MySandboxGame.Update()
   at Sandbox.Engine.Platform.Game.UpdateInternal()
   at Sandbox.Engine.Platform.Game.RunSingleFrame()
   at Sandbox.Engine.Platform.FixedLoop.<>c__DisplayClass11_0.<Run>b__0()
   at Sandbox.Engine.Platform.GenericLoop.Run(VoidAction tickCallback)
   at Sandbox.Engine.Platform.Game.RunLoop()
   at Sandbox.MySandboxGame.Run(Boolean customRenderLoop, Action disposeSplashScreen)
   at SpaceEngineers.MyProgram.Main(String[] args)

**Comment by cKerenskySE** [comment]
Specifically, this issue is caused when applying a name Prefix to a Container that does not have a custom name (IE: Large Cargo Container)
Either checking - and then setting the value to an empty string, or just skipping it if there's no custom name, both fix the problem.

**Comment by MeridiusIX** [comment]
This should be fixed in an update that went out a while ago
