### ISSUE TITLE
Server Crash at ModularEncountersSystems.Entities.EntityEvaluator.GetGridOwnerships

### ISSUE THREAD

**Issue by kaliber64** [MeridiusIX/Modular-Encounters-Systems#202]
Crash during normal operation of server. This has happened a couple times. About once every 1 to 2 days it happens.

2022-05-10 16:44:39.712 - Thread:   1 ->  GC Memory: 1813.793 / 1813.793 MB
2022-05-10 16:44:44.482 - Thread:   1 ->  Exception occurred: System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at ModularEncountersSystems.Entities.EntityEvaluator.GetGridOwnerships(List`1 gridList, Boolean overrideCheck)
   at ModularEncountersSystems.Entities.GridEntity.OwnershipChange(IMyCubeGrid cubeGrid)
   at Sandbox.Game.Entities.MyCubeGrid.NotifyBlockOwnershipChange()
   at Sandbox.Game.Entities.Cube.MyCubeGridOwnershipManager.RecalculateOwnersInternal(Boolean updatePlayerGrids)
   at Sandbox.Game.Entities.MyCubeGrid.Dispatch(UpdateQueue queue, Boolean parallel)
   at Sandbox.Game.Entities.MyCubeGrid.UpdateAfterSimulation()
   at Sandbox.Game.Entities.MyParallelEntityUpdateOrchestrator.UpdateAfterSimulation()
   at Sandbox.Game.Entities.MyParallelEntityUpdateOrchestrator.DispatchAfterSimulation()
   at Sandbox.Game.Entities.MyEntities.UpdateAfterSimulation()
   at Sandbox.Game.World.MySector.UpdateAfterSimulation()
   at Sandbox.Game.World.MySession.UpdateComponents()
   at Sandbox.Game.World.MySession.Update(MyTimeSpan updateTime)
   at Sandbox.MySandboxGame.Update()
   at Sandbox.Engine.Platform.Game.UpdateInternal()
   at Sandbox.Engine.Platform.Game.RunSingleFrame()
   at Sandbox.Engine.Platform.FixedLoop.<>c__DisplayClass11_0.<Run>b__0()
   at Sandbox.Engine.Platform.GenericLoop.Run(VoidAction tickCallback)
   at Sandbox.Engine.Platform.Game.RunLoop()
   at Sandbox.MySandboxGame.Run(Boolean customRenderLoop, Action disposeSplashScreen)
   at VRage.Dedicated.DedicatedServer.RunInternal(String instanceName)
   at VRage.Dedicated.DedicatedServer.RunMain(String instanceName, String customPath, Boolean isService, Boolean showConsole, Boolean checkAlive)
   at VRage.Dedicated.DedicatedServer.ProcessArgs(String[] args)
   at VRage.Dedicated.DedicatedServer.Run(String[] args, Action`1 initializeServices)
   at SpaceEngineersDedicated.MyProgram.Main(String[] args)
2022-05-10 16:44:44.483 - Thread:   1 ->  Showing message
2022-05-10 16:44:47.271 - Thread:   1 ->  
================================== CRASH INFO ==================================
AppVersion: 01_201_013
GameName: Space Engineers
IsOutOfMemory: False
IsGPU: False
IsNative: False
IsTask: False
IsExperimental: True
ProcessRunTime: 67150
PCUCount: 213649
IsHang: False
GCMemory: 1819
GCMemoryAllocated: 1819
HWAvailableMemory: 18937
ProcessPrivateMemory: 5261
AnalyticId: SEDS

Mod List: Attached

[ModList.txt](https://github.com/MeridiusIX/Modular-Encounters-Systems/files/8664898/ModList.txt)

**Comment by MeridiusIX** [comment]
Thanks, I'll attempt a fix in the next update

**Comment by Mrbu9gle** [comment]
I am also having this exact  fatal exception also, started after the last game update for us. I found enteries in both the keen log and the torch log referencing the same exception.
