### ISSUE TITLE
Latest patch breaks WaveSpawner in standard config

### ISSUE THREAD

**Issue by s-reich** [MeridiusIX/Modular-Encounters-Systems#227]
Exception in Log:
````
20:47:27.3077 [FATAL]  Initializer: System.NullReferenceException: Object reference not set to an instance of an object.
   at ModularEncountersSystems.Spawning.SpawnGroupManager.GetSpawnGroups(SpawningType type, EnvironmentEvaluation environment, String overrideFaction, SpawnGroupCollection collection, Boolean forceSpawn, Boolean adminSpawn, List`1 eligibleNames, Dictionary`2 playerDroneTracker)
   at ModularEncountersSystems.Spawning.SpawnRequest.CalculateSpawn(Vector3D coords, String source, SpawningType type, Boolean forceSpawn, Boolean adminSpawn, List`1 eligibleNames, String factionOverride, MatrixD spawnMatrix, Vector3D customVelocity)
   at ModularEncountersSystems.Spawning.WaveSpawner.ActiveSpawnerProcessing()
   at System.Action.Invoke()
   at ModularEncountersSystems.Tasks.SubscribeTask.Run()
   at ModularEncountersSystems.Tasks.TaskProcessor.Process()
   at ModularEncountersSystems.Core.MES_SessionCore.UpdateBeforeSimulation()
   at Patched_Sandbox.Game.World.MySessionUpdateComponents_0(Object )
   at Patched_Sandbox.Game.World.MySessionUpdate_0(Object , MyTimeSpan )
   at Sandbox.MySandboxGame.Update()
   at Patched_Sandbox.Engine.Platform.GameUpdateInternal_0(Object )
   at Patched_Sandbox.Engine.Platform.GameRunSingleFrame_0(Object )
   at Patched_Sandbox.Engine.Platform.FixedLoop+<>c__DisplayClass11_0<Run>b__0_0(Object )
   at Sandbox.Engine.Platform.GenericLoop.Run(VoidAction tickCallback)
   at Sandbox.Engine.Platform.Game.RunLoop()
   at Sandbox.MySandboxGame.Run(Boolean customRenderLoop, Action disposeSplashScreen)
   at Torch.VRageGame.DoStart() in C:\ProgramData\Jenkins\.jenkins\workspace\Torch_master\Torch\VRageGame.cs:line 316
   at Torch.VRageGame.Run() in C:\ProgramData\Jenkins\.jenkins\workspace\Torch_master\Torch\VRageGame.cs:line 130
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
````

Problematic code from commit e0993748ac4edbb199bceb26fc1e1df52b4c457f:

````
SpawnGroupManager.cs:326

if (spawnGroup.SpawnConditionsProfiles.Count == conditionsFailedBySpawnType || (adminSpawn && !eligibleNames.Contains(spawnGroup.SpawnGroupName))) {
````

...`eligibleNames` is null here.

**Comment by pfthroaway** [comment]
I'm also having this issue with spawners, but my log is a bit different.

```
19:44:14.996 - Thread:   1 ->  Exception occurred: System.NullReferenceException: Object reference not set to an instance of an object.
   at ModularEncountersSystems.Spawning.SpawnGroupManager.GetSpawnGroups(SpawningType type, EnvironmentEvaluation environment, String overrideFaction, SpawnGroupCollection collection, Boolean forceSpawn, Boolean adminSpawn, List`1 eligibleNames, Dictionary`2 playerDroneTracker)
   at ModularEncountersSystems.Spawning.SpawnRequest.CalculateSpawn(Vector3D coords, String source, SpawningType type, Boolean forceSpawn, Boolean adminSpawn, List`1 eligibleNames, String factionOverride, MatrixD spawnMatrix, Vector3D customVelocity)
   at ModularEncountersSystems.Spawning.WaveSpawner.ActiveSpawnerProcessing()
   at System.Action.Invoke()
   at ModularEncountersSystems.Tasks.SubscribeTask.Run()
   at ModularEncountersSystems.Tasks.TaskProcessor.Process()
   at ModularEncountersSystems.Core.MES_SessionCore.UpdateBeforeSimulation()
   at Sandbox.Game.World.MySession.UpdateComponents()
   at Sandbox.Game.World.MySession.Update(MyTimeSpan updateTime)
   at Sandbox.MySandboxGame.Update()
   at Sandbox.Engine.Platform.Game.UpdateInternal()
   at Sandbox.Engine.Platform.Game.RunSingleFrame()
   at Sandbox.Engine.Platform.FixedLoop.<>c__DisplayClass11_0.<Run>b__0()
   at Sandbox.Engine.Platform.GenericLoop.Run(VoidAction tickCallback)
   at Sandbox.Engine.Platform.Game.RunLoop()
   at Sandbox.MySandboxGame.Run(Boolean customRenderLoop, Action disposeSplashScreen)
   at SpaceEngineers.MyProgram.Main(String[] args)
```

**Comment by iceystreet** [comment]
Having same issue my instances are crashing on wave spawner

11:39:31.2038 [FATAL]  Initializer: System.NullReferenceException: Object reference not set to an instance of an object.
   at ModularEncountersSystems.Spawning.SpawnGroupManager.GetSpawnGroups(SpawningType type, EnvironmentEvaluation environment, String overrideFaction, SpawnGroupCollection collection, Boolean forceSpawn, Boolean adminSpawn, List`1 eligibleNames, Dictionary`2 playerDroneTracker)
   at ModularEncountersSystems.Spawning.SpawnRequest.CalculateSpawn(Vector3D coords, String source, SpawningType type, Boolean forceSpawn, Boolean adminSpawn, List`1 eligibleNames, String factionOverride, MatrixD spawnMatrix, Vector3D customVelocity)
   at ModularEncountersSystems.Spawning.WaveSpawner.ActiveSpawnerProcessing()
   at System.Action.Invoke()
   at ModularEncountersSystems.Tasks.TaskProcessor.Process()
   at Sandbox.Game.World.MySession.UpdateComponents()
   at Sandbox.Game.World.MySession.Update(MyTimeSpan updateTime)
   at Sandbox.MySandboxGame.Update()
   at Sandbox.Engine.Platform.Game.UpdateInternal()
   at Sandbox.Engine.Platform.Game.RunSingleFrame()
   at Sandbox.Engine.Platform.FixedLoop.<>c__DisplayClass11_0.<Run>b__0()
   at Sandbox.Engine.Platform.GenericLoop.Run(VoidAction tickCallback)
   at Sandbox.Engine.Platform.Game.RunLoop()
   at Sandbox.MySandboxGame.Run(Boolean customRenderLoop, Action disposeSplashScreen)
   at Torch.VRageGame.DoStart() in C:\ProgramData\Jenkins\.jenkins\workspace\Torch_master\Torch\VRageGame.cs:line 316
   at Torch.VRageGame.Run() in C:\ProgramData\Jenkins\.jenkins\workspace\Torch_master\Torch\VRageGame.cs:line 130
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
System.NullReferenceException: Object reference not set to an instance of an object.
   at ModularEncountersSystems.Spawning.SpawnGroupManager.GetSpawnGroups(SpawningType type, EnvironmentEvaluation environment, String overrideFaction, SpawnGroupCollection collection, Boolean forceSpawn, Boolean adminSpawn, List`1 eligibleNames, Dictionary`2 playerDroneTracker)
   at ModularEncountersSystems.Spawning.SpawnRequest.CalculateSpawn(Vector3D coords, String source, SpawningType type, Boolean forceSpawn, Boolean adminSpawn, List`1 eligibleNames, String factionOverride, MatrixD spawnMatrix, Vector3D customVelocity)
   at ModularEncountersSystems.Spawning.WaveSpawner.ActiveSpawnerProcessing()
   at System.Action.Invoke()
   at ModularEncountersSystems.Tasks.TaskProcessor.Process()
   at Sandbox.Game.World.MySession.UpdateComponents()
   at Sandbox.Game.World.MySession.Update(MyTimeSpan updateTime)
   at Sandbox.MySandboxGame.Update()
   at Sandbox.Engine.Platform.Game.UpdateInternal()
   at Sandbox.Engine.Platform.Game.RunSingleFrame()
   at Sandbox.Engine.Platform.FixedLoop.<>c__DisplayClass11_0.<Run>b__0()
   at Sandbox.Engine.Platform.GenericLoop.Run(VoidAction tickCallback)
   at Sandbox.Engine.Platform.Game.RunLoop()
   at Sandbox.MySandboxGame.Run(Boolean customRenderLoop, Action disposeSplashScreen)
   at Torch.VRageGame.DoStart() in C:\ProgramData\Jenkins\.jenkins\workspace\Torch_master\Torch\VRageGame.cs:line 316
   at Torch.VRageGame.Run() in C:\ProgramData\Jenkins\.jenkins\workspace\Torch_master\Torch\VRageGame.cs:line 130
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

**Comment by MeridiusIX** [comment]
Hoxfixed and uploaded to steam.

**Comment by s-reich** [comment]
Great response time!
Looking forward to get visitors again :)
