### ISSUE TITLE
Game crashes every 5 mins when trying to spawn a cargo/enemy ship ever since i added eem to the world which i have removed but continues to crash every 5 mins

### ISSUE THREAD

**Issue by copster219** [MeridiusIX/Modular-Encounters-Systems#285]
ever since i added eem to the world which i have removed now but MES continues to crash every 5 mins 
and any help would be amazing thanks and heres what i found in the log 

 Thread:  13 ->  MES Spawner / Error: Could Not Add Trigger Profile To Behavior: [SurfaceOccupation-Trigger-CallAtmoCargoShip]
2023-11-20 08:55:13.598 - Thread:  16 ->  MES Spawner / Error: Could Not Add Trigger Profile To Behavior: [TOC-Trigger-CreateSafeZone]
2023-11-20 08:55:13.598 - Thread:  14 ->  MES Spawner / Error: Could Not Add Trigger Profile To Behavior: [TOC-Trigger-CreateSafeZone]
2023-11-20 08:55:13.598 - Thread:  16 ->  MES Spawner / Error: Could Not Add Trigger Profile To Behavior: [TOC-Trigger-CallCargoShip]
2023-11-20 08:55:13.598 - Thread:  14 ->  MES Spawner / Error: Could Not Add Trigger Profile To Behavior: [TOC-Trigger-CallCargoShip]
2023-11-20 08:55:13.598 - Thread:  16 ->  MES Spawner / Error: Could Not Add Trigger Profile To Behavior: [TOC-Trigger-CargoShipArrival]
2023-11-20 08:55:13.598 - Thread:  14 ->  MES Spawner / Error: Could Not Add Trigger Profile To Behavior: [TOC-Trigger-CargoShipArrival]
2023-11-20 08:55:13.598 - Thread:  16 ->  MES Spawner / Error: Could Not Add Trigger Profile To Behavior: [TOC-Trigger-RefreshBasicStores]
2023-11-20 08:55:13.599 - Thread:  14 ->  MES Spawner / Error: Could Not Add Trigger Profile To Behavior: [TOC-Trigger-RefreshBasicStores]
2023-11-20 08:55:13.644 - Thread:  15 ->  MES Spawner / Error: Could Not Add Trigger Profile To Behavior: [ASE-T-ATM-Claim-T2]
2023-11-20 08:55:13.644 - Thread:  15 ->  MES Spawner / Error: Could Not Add Trigger Profile To Behavior: [ASE-T-ATM-DNSK-Populated]
2023-11-20 08:55:13.644 - Thread:  13 ->  MES Spawner / Error: Could Not Add Trigger Profile To Behavior: [ASE-T-ATM-Claim-T2]
2023-11-20 08:55:13.644 - Thread:  13 ->  MES Spawner / Error: Could Not Add Trigger Profile To Behavior: [ASE-T-ATM-DNSK-Populated]
2023-11-20 08:55:13.644 - Thread:  16 ->  MES Spawner / Error: Could Not Add Trigger Profile To Behavior: [ASE-T-ATM-Claim-T2]
2023-11-20 08:55:13.644 - Thread:  16 ->  MES Spawner / Error: Could Not Add Trigger Profile To Behavior: [ASE-T-ATM-DNSK-Populated]
2023-11-20 08:55:23.080 - Thread:   1 ->  MyGuiScreenDebugOfficial MyGuiScreenBase.UnloadContent - START
2023-11-20 08:55:23.080 - Thread:   1 ->  MyGuiScreenDebugOfficial MyGuiScreenBase.UnloadContent - END
2023-11-20 08:55:24.446 - Thread:   1 ->  MyGuiScreenChat.ctor START
2023-11-20 08:55:24.447 - Thread:   1 ->  MyGuiScreenChat.ctor END
2023-11-20 08:55:24.459 - Thread:   1 ->  MyGuiScreenChat MyGuiScreenBase.LoadContent
2023-11-20 08:55:25.416 - Thread:   1 ->  MES Spawner / SpawnRecord: WARNING: Spawning NPC Grids beyond 6500km from world center may result in loss of precision when grids are placed in the world or when they utilize path finding. This is because of game engine limitations.
2023-11-20 08:55:25.507 - Thread:   1 ->  MyGuiScreenChat MyGuiScreenBase.UnloadContent - START
2023-11-20 08:55:25.507 - Thread:   1 ->  MyGuiScreenChat MyGuiScreenBase.UnloadContent - END
2023-11-20 08:55:25.528 - Thread:   1 ->  Exception occurred: System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Enumerator.MoveNext()
   at VRage.Game.Components.MyComponentContainer.Serialize(Boolean copy)
   at Sandbox.Game.Entities.MyCubeBlock.GetObjectBuilderCubeBlock(Boolean copy)
   at Sandbox.Game.Entities.Cube.MyTerminalBlock.GetObjectBuilderCubeBlock(Boolean copy)
   at Sandbox.Game.Entities.Cube.MyFunctionalBlock.GetObjectBuilderCubeBlock(Boolean copy)
   at Sandbox.Game.Entities.MyBatteryBlock.GetObjectBuilderCubeBlock(Boolean copy)
   at Sandbox.Game.Entities.Cube.MySlimBlock.GetObjectBuilderInternal(Boolean copy)
   at Sandbox.Game.Entities.MyCubeGrid.GetObjectBuilderInternal(MyObjectBuilder_CubeGrid ob, Boolean copy)
   at Sandbox.Game.Entities.MyCubeGrid.GetObjectBuilder(Boolean copy)
   at Yellajacket_HomingMissiles.Yellajacket_HomingMissiles_SessionCore.EntityCheck(IMyEntity entity)
   at System.Action`1.Invoke(T obj)
   at Sandbox.Game.Entities.MyEntities.RaiseEntityAdd(MyEntity entity)
   at Sandbox.Game.Entities.MyEntities.Add(MyEntity entity, Boolean insertIntoScene)
   at Sandbox.Game.World.MyPrefabManager.CreateGridsData.OnGridsCreated(WorkData workData)
   at ParallelTasks.Parallel.RunCallbacks()
   at Sandbox.Game.World.MySession.Update(MyTimeSpan updateTime)
   at Sandbox.MySandboxGame.Update()
   at Sandbox.Engine.Platform.Game.UpdateInternal()
   at Sandbox.Engine.Platform.Game.RunSingleFrame()
   at Sandbox.Engine.Platform.FixedLoop.<>c__DisplayClass11_0.<Run>b__0()
   at Sandbox.Engine.Platform.GenericLoop.Run(VoidAction tickCallback)
   at Sandbox.Engine.Platform.Game.RunLoop()
   at Sandbox.MySandboxGame.Run(Boolean customRenderLoop, Action disposeSplashScreen)
   at SpaceEngineers.MyProgram.Main(String[] args)
2023-11-20 08:55:25.529 - Thread:   1 ->  Showing message
2023-11-20 08:55:27.688 - Thread:   1 ->  
================================== CRASH INFO ==================================
AppVersion: 01_203_505
GameName: Space Engineers
IsOutOfMemory: False
IsGPU: False
IsNative: False
IsTask: False
IsExperimental: True
ProcessRunTime: 355
PCUCount: 542838
IsHang: False
GCMemory: 4350
GCMemoryAllocated: 4350
HWAvailableMemory: 8845
ProcessPrivateMemory: 18281
AnalyticId: SE
================================== OFNI HSARC ==================================

2023-11-20 08:55:27.689 - Thread:   1 ->  Log Closed

**Comment by MeridiusIX** [comment]
Not related to MES. Stacktrace refrences `Yellajacket_HomingMissiles` as part of the exception.
