### ISSUE TITLE
NRE: PrefabManipulation Preparation

### ISSUE THREAD

**Issue by MeridiusIX** [MeridiusIX/Modular-Encounters-Systems#57]
```
2021-08-13 20:36:56.818 - Thread:   1 ->  Exception occurred: System.NullReferenceException: Object reference not set to an instance of an object.
   at ModularEncountersSpawner.Manipulation.ManipulationCore.ProcessPrefabForManipulation(String prefabName, ImprovedSpawnGroup spawnGroup, String spawnType, String behavior)
   at ModularEncountersSpawner.Spawners.PlanetaryInstallationSpawner.AttemptSpawn(Vector3D startCoords, IMyPlayer player, List`1 eligibleNames)
   at ModularEncountersSpawner.MES_SessionCore.ProcessPlayerWatchList()
   at ModularEncountersSpawner.MES_SessionCore.UpdateBeforeSimulation()
   at Sandbox.Game.World.MySession.UpdateComponents()
   at Sandbox.Game.World.MySession.Update(MyTimeSpan updateTime)
   at Sandbox.MySandboxGame.Update()
   at Sandbox.Engine.Platform.Game.UpdateInternal()
   at Sandbox.Engine.Platform.Game.RunSingleFrame()
   at Sandbox.Engine.Platform.FixedLoop.<>c__DisplayClass11_0.<Run>b__0()
   at Sandbox.Engine.Platform.GenericLoop.Run(VoidAction tickCallback)
   at Sandbox.Engine.Platform.Game.RunLoop()
   at Sandbox.MySandboxGame.Run(Boolean customRenderLoop, Action disposeSplashScreen)
   at SpaceEngineers.MyProgram.Main(String[] args)
```

**Comment by MeridiusIX** [comment]
Bug is not in the rewrite
