### ISSUE TITLE
Key Not Found Bug: Definition Helper Setup

### ISSUE THREAD

**Issue by MeridiusIX** [MeridiusIX/Modular-Encounters-Systems#58]
Exception occurred: System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
at System.ThrowHelper.ThrowKeyNotFoundException()
at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
at ModularEncountersSystems.Helpers.DefinitionHelper.Setup()
at ModularEncountersSystems.Core.MES_SessionCore.LoadData()
at Sandbox.Game.World.MySession.LoadComponent(MySessionComponentBase component)

**Comment by MeridiusIX** [comment]
Fixed the only direct key access in that method. Hopefully does the trick. I'll need to see if that player gets the same issue after I publish this batch of changes

**Comment by MeridiusIX** [comment]
Bug ain't dead, need a bigger shoe
